web:
  image: nginx:latest
  ports:
    - "8181:80"
  volumes:
    - ./website:/code
    - ./site.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
php:
  image: php:7-fpm
  volumes:
    - ./website:/code
    - ./env.conf:/usr/local/etc/php-fpm.d/env.conf
  env_file: 
    - php.env
